### ISSUE TITLE
accelerometer crash

### ISSUE THREAD

**Issue by mattpadams** [mjl68/FallAssistant#1]
05-06 04:51:47.402    3676-3816/com.falldetect2015.android.fallassistant E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-113574
    Process: com.falldetect2015.android.fallassistant, PID: 3676
    java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
            at android.os.Handler.<init>(Handler.java:200)
            at android.os.Handler.<init>(Handler.java:114)
            at android.os.CountDownTimer$1.<init>(CountDownTimer.java:114)
            at android.os.CountDownTimer.<init>(CountDownTimer.java:114)
            at com.falldetect2015.android.fallassistant.faSensorService$2.<init>(faSensorService.java:209)
            at com.falldetect2015.android.fallassistant.faSensorService.detectMovement(faSensorService.java:209)
            at com.falldetect2015.android.fallassistant.faSensorService$1.run(faSensorService.java:192)
            at java.lang.Thread.run(Thread.java:818)

**Comment by mjl68** [comment]
I've been working on it...trying to get settings to work also.
